<div class="hero">
    <h3>Bienvenido al RestAPI</h3>
    <p>Llamadas para consumir el rest</p>
    <ul>
      <li>Método para obtener todos los usuarios GET http://localhost/backendcts/api/usuario</li>
      <li>Método para obtener un usuario GET http://localhost/backendcts/api/usuario/{$id}</li>
      <li>Método para crear un usuario POST http://localhost/backendcts/api/usuario/{$id}</li>
      <li>Método para editar un usuario PUT http://localhost/backendcts/api/usuario/{$id}</li>
      <li>Método para eliminar un usuario DELETE http://localhost/backendcts/api/usuario/{$id}</li>
    </ul>
   <?= Html::link('pages/show/kumbia/status/', 'Ver Config', 'title="Ver configuración de la aplicación" class="btn btn-info"') ?>
</div>
<h2>Cómo empezar</h2>
<p>En nuestra <a href="http://wiki.kumbiaphp.com/">wiki</a> podrás encontrar información actualizada sobre el uso del framework,
si estas comenzando con <em>KumbiaPHP</em> deberías realizar  la
<strong><a href="http://wiki.kumbiaphp.com/Hola_Mundo_KumbiaPHP_Framework">Aplicación Hola Mundo</a></strong>.</p>
<p>También puede interesarte saber sobre:</p>
